name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Executa todo dia à meia-noite (UTC)
  workflow_dispatch: # Permite execução manual na aba Actions

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: BoringBoredom/PC-Optimization-Hub
          upstream_sync_branch: main # <-- A branch do original
          target_sync_branch: main # <-- A sua branch que será atualizada
          upstream_pull_args: '--allow-unrelated-histories'
          
          # Token para autenticação
          github_token: ${{ secrets.GITHUB_TOKEN }}
